[package]
name = "lutz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
image = "0.23.14"
imageproc = "0.22.0"
criterion = "0.3"
peak_alloc = "0.1.0"

[[bench]]
name = "bench"
harness = false
