[package]
name = "lutz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
image = "0.23.14"

[dependencies]
imageproc = "0.22.0"
